# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoWeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoWeatherApp
  pod 'Alamofire'

  target 'PhotoWeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoWeatherAppUITests' do
    # Pods for testing
  end

end
